app/urls.py
from django.urls import path

from app import views as app_views

urlpatterns = [  # pylint: disable=invalid-name
    path('', app_views.index, name='index'),
    path('project/', app_views.add_project, name='add-project'),
    path('project/<int:project_id>/', app_views.project_details, name='project-details'),
    path('project/<int:project_id>/timetable', app_views.project_timetable,
         name='project-timetable'),
    path('project/<int:project_id>/text/<int:task_id>/', app_views.text, name='text'),
    path('project/<int:project_id>/text/<int:task_id>/<int:progress>', app_views.text, name='text'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [  # pylint: disable=invalid-name
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('app.urls')),
    path('table/', include('table.urls', namespace='table')),
]

if settings.USE_LOCAL_API:
    urlpatterns.append(path('dummy/', include('dummy_api.urls', namespace='dummy')))

table/urls.py
""" URLs for `table` app """
from django.urls import path

from table import views

urlpatterns = [
    path('', views.view_tasks, name='table'),
    path('track', views.track, name='track'),
]
app_name = 'table'

table/models.py
""" Models for `table` app """
from django.contrib.auth.models import User
from django.db import models

from table.constants import TaskStatus


class Task(models.Model):
    """ Task to be performed """
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=128)
    # Making this a URLField doesn't allow deep links, so we use an unvalidated CharField
    url = models.CharField(blank=True, max_length=200)
    active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name


class TaskInstance(models.Model):
    """ Whether a task was performed on a given day """
    task = models.ForeignKey(Task, on_delete=models.PROTECT)
    date = models.DateField()
    status = models.CharField(max_length=32, choices=TaskStatus.choices)
    
    def __str__(self):
        if 'task' in self._state.fields_cache:
            # The query to fetch the task has already been made
            return f'{self.task} on {self.date}'
        else:
            return f'Task #{self.task_id} on {self.date}'
    
    class Meta:
        unique_together = ('task', 'date')

table/forms.py
""" Forms for `table` app """
from django import forms

from table.constants import TaskStatus
from table.models import Task


class TaskInstanceForm(forms.Form):
    """ Form for updating a TaskInstance """
    date = forms.DateField()
    status = forms.ChoiceField(choices=TaskStatus.choices)
    task = forms.ModelChoiceField(queryset=Task.objects.all())
    
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['task'].queryset = Task.objects.filter(user=user)

table/views.py
""" Views for `table` app """
import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.utils import timezone

from table import helpers
from table.forms import TaskInstanceForm
from table.models import TaskInstance


@login_required
def track(request):
    """ Allow a user to track their tasks """
    if request.method == 'POST':
        form = TaskInstanceForm(request.user, request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            date = form.cleaned_data['date']
            task_instance, _ = TaskInstance.objects.get_or_create(date=date, task=task)
            task_instance.status = form.cleaned_data['status']
            task_instance.save()
            # Redirect to this same page with the same query parameters
            return redirect(request.get_full_path())
    
    user = request.user
    try:
        date = datetime.date.fromisoformat(request.GET.get('date', ''))
    except ValueError:
        # Empty or invalid parameter
        date = helpers.get_date(user)
    tasks = helpers.get_task_list(user, date)
    context = {
        'date': date,
        'tasks': tasks,
    }
    return render(request, 'table/tracking.html', context)


@login_required
def view_tasks(request):
    """ Show a user their completed tasks in table form """
    today = timezone.localdate()
    try:
        start_date = datetime.date.fromisoformat(request.GET.get('start', ''))
    except ValueError:
        # Empty or invalid parameter
        start_date = today - datetime.timedelta(days=30)
    try:
        end_date = datetime.date.fromisoformat(request.GET.get('end', ''))
    except ValueError:
        # Empty or invalid parameter
        end_date = today
    
    tasks = TaskInstance.objects.filter(
        date__gte=start_date,
        date__lte=end_date,
        task__user=request.user,
    ).values_list('task__name', 'date', 'status')
    name_list = list({name for name, _, _ in tasks})
    date_list = sorted({date for _, date, _ in tasks})
    status_mapping = {(name, date): status for name, date, status in tasks}
    task_display = [(name, [
        helpers.status_symbol(status_mapping.get((name, date), None)) for date in date_list
    ]) for name in name_list]
    context = {
        'dates': date_list,
        'end_date': end_date,
        'start_date': start_date,
        'tasks': task_display,
    }
    return render(request, 'table/table.html', context)

table/templates/table/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Tasks</title>
  {% block static %}{% endblock %}
  <link rel="stylesheet" href="{% static 'css/common.css' %}">
</head>
<body>
<nav>
  <a href="{% url 'table:track' %}">Track</a>
  <a href="{% url 'table:table' %}">View Table</a>
  {% if user.is_staff %}
    <a href="{% url 'admin:index' %}">Admin</a>
  {% endif %}
  {% if user.is_authenticated %}
    <a href="{% url 'logout' %}">Log Out</a>
  {% else %}
    <a href="{% url 'login' %}">Log In</a>
  {% endif %}
</nav>
{% block body %}{% endblock %}
</body>
</html>

table/templates/table/table.html
{% extends 'table/base.html' %}
{% load static %}

{% block body %}
  <h1>Completed tasks</h1>
  <form method="get">
    <label for="display-start">Start Date:</label>
    <input id="display-start" name="start" type="date" value="{{ start_date.isoformat }}">
    <br>
    <label for="display-end">End Date:</label>
    <input id="display-end" name="end" type="date" value="{{ end_date.isoformat }}">
    <br>
    <button type="submit">Change Dates</button>
  </form>
  <br>
  
  <table>
    <thead>
    <tr>
      <th>{# Blank #}</th>
      {% for date in dates %}
        <th>{{ date }}</th>
      {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for name, row in tasks %}
      <tr>
        <th scope="row">{{ name }}</th>
        {% for cell in row %}
          <td>{{ cell }}</td>
        {% endfor %}
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

{% block static %}
  <link href="{% static 'css/table.css' %}" rel="stylesheet">
{% endblock %}

table/templates/table/tracking.html
{% extends 'table/base.html' %}
{% load static %}

{% block body %}
  <h1>Tracking tasks</h1>
  <form method="get">
    <label for="display-date">Date:</label>
    <input id="display-date" name="date" type="date" value="{{ date.isoformat }}">
    <br>
    <button type="submit">Change Date</button>
  </form>
  <br>
  
  {% for task in tasks %}
    <span>{{ task.name }}</span>
    {% if task.url %}
    <a class="task-link" href="{{ task.url }}" target="_blank">&rarr;</a>
    {% endif %}
    <form method="post">
      {% csrf_token %}
      <input name="task" type="hidden" value="{{ task.pk }}">
      <input name="date" type="hidden" value="{{ date.isoformat }}">
      <span class="button-holder {% if task.status == 'success' %}active{% endif %}">
        <button name="status" type="submit" value="success">Done</button>
      </span>
      <span class="button-holder {% if task.status == 'fail' %}active{% endif %}">
        <button name="status" type="submit" value="fail">Not Done</button>
      </span>
      <span class="button-holder {% if task.status == 'pass' %}active{% endif %}">
        <button name="status" type="submit" value="pass">Pass</button>
      </span>
    </form>
    <br>
  {% endfor %}
{% endblock %}

{% block static %}
  <link href="{% static 'css/table.css' %}" rel="stylesheet">
{% endblock %}